# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class TestSearchingsubstance():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchingsubstance(self):
    self.driver.get("https://chem.echa.europa.eu/")
    self.driver.set_window_size(514, 683)
    element = WebDriverWait(self.driver, 30).until(EC.visibility_of_element_located((By.XPATH, "//iucdas-mod-substance-search-app")))

    element.click()


TestSearchingsubstance.test_searchingsubstance()

